
plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = '1.0.0'
group = 'com.horsemeat'

base {
    archivesName = 'horsemeat'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

neoForge {
    version = '26.2.0.87'
    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', 'horsemeat'
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'horsemeat'
        }
    }
    mods {
        horsemeat {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // NeoForge modding dependencies
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version: '26.2',
            minecraft_version_range: '[26.2,26.3)',
            neo_version: '26.2.0.87',
            neo_version_range: '[26.2.0.87,)',
            loader_version_range: '[4,)',
            mod_id: 'horsemeat',
            mod_name: 'Horse Meat Mod',
            mod_license: 'All Rights Reserved',
            mod_version: '1.0.0',
            mod_authors: 'Gargoyle',
            mod_description: 'Extra meat drops from horses!'
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

