# Gradle JVM memory
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true

# NeoForge
neo_version=26.2.0.87
minecraft_version=26.2

# Mod info
mod_id=horsemeat
mod_name=Horse Meat Mod
mod_version=1.0.1
mod_group_id=com.horsemeat
mod_authors=Gargoyle
mod_license=All Rights Reserved
mod_description='''Extra meat drops from horses!'''
