modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/djroberts/minecraft-mods/issues"

[[mods]]
modId="horsemeat"
version="1.0.0"
displayName="Horse Meat Mod"
authors="Gargoyle"
description="Extra meat drops from horses!"

[[dependencies.horsemeat]]
modId="neoforge"
type="required"
versionRange="[26.2.0.87,)"
ordering="NONE"
side="BOTH"

[[dependencies.horsemeat]]
modId="minecraft"
type="required"
versionRange="[26.2,26.3)"
ordering="NONE"
side="BOTH"
